[package]
edition = "2021"
name = "shift-font"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
fontc = "0.2.0"
norad = "0.16.0"
serde = "1.0.219"
skrifa = "0.32.0"
ts-rs = "11.0.1"

[profile.release]
lto = true
strip = "symbols"
